name: uhc
main: vch.uhc.UHC
version: 1.0.2
api-version: 1.21
depend: [TAB, PlaceholderAPI]
commands:
  uhc:
    description: Main UHC command
    usage: /uhc <subcommand>
    permission: uhc.use
    aliases: [uhc]
    children:
      info:
        description: Show UHC information
        permission: uhc.info
      start:
        description: Start the UHC game
        permission: uhc.start
      cancel:
        description: Cancel the UHC game
        permission: uhc.cancel
      reload:
        description: Reload the plugin
        permission: uhc.reload
      pause:
        description: Pause the UHC game
        permission: uhc.pause
      join:
        description: Join the UHC game
        permission: uhc.join
      leave:
        description: Leave the UHC game
        permission: uhc.leave
      players:
        description: Player management
        permission: uhc.players
      settings:
        description: Change UHC settings
        permission: uhc.settings
      menu:
        description: Open the settings menu
        permission: uhc.menu
      stats:
        description: Show game statistics
        permission: uhc.stats
      afk:
        description: Toggle AFK mode
        permission: uhc.afk
      team:
        description: Team management
        permission: uhc.team
        children:
          create:
            permission: uhc.team.create
          add:
            permission: uhc.team.add
          remove:
            permission: uhc.team.remove
          rename:
            permission: uhc.team.rename
          leave:
            permission: uhc.team.leave
          list:
            permission: uhc.team.list

permissions:
  uhc.admin:
    description: Full access to all UHC commands
    default: op
    children:
      uhc.use: true
      uhc.info: true
      uhc.start: true
      uhc.cancel: true
      uhc.reload: true
      uhc.pause: true
      uhc.join: true
      uhc.leave: true
      uhc.players: true
      uhc.settings: true
      uhc.menu: true
      uhc.stats: true
      uhc.team: true
      uhc.team.create: true
      uhc.team.add: true
      uhc.team.remove: true
      uhc.team.list: true
      uhc.team.leave: true
      uhc.afk: true
  uhc.use:
    description: Base permission for UHC commands
    default: true
  uhc.info:
    description: Permission to view UHC info
    default: op
  uhc.start:
    description: Permission to start UHC
    default: op
  uhc.cancel:
    description: Permission to cancel UHC
    default: op
  uhc.reload:
    description: Permission to reload UHC
    default: op
  uhc.pause:
    description: Permission to pause UHC
    default: op
  uhc.join:
    description: Permission to join UHC
    default: op
  uhc.leave:
    description: Permission to leave UHC
    default: true
  uhc.stats:
    description: Permission to view stats
    default: true
  uhc.menu:
    description: Permission to open settings menu
    default: op
  uhc.afk:
    description: Permission to toggle AFK
    default: true
  uhc.settings:
    description: Permission to change settings
    default: op
    children:
      uhc.settings.set: true
  uhc.settings.set:
    default: op
  uhc.players:
    description: Permission for player management
    default: op
    children:
      uhc.players.list: true
      uhc.players.setLives: true
      uhc.players.setHealth: true
      uhc.players.revive: true
  uhc.players.list:
    default: op
  uhc.players.setLives:
    default: op
  uhc.players.setHealth:
    default: op
  uhc.players.revive:
    default: op
  uhc.team:
    description: Base permission for team commands
    default: true
  uhc.team.create:
    default: op
  uhc.team.add:
    default: op
  uhc.team.remove:
    default: op
  uhc.team.rename:
    default: true
  uhc.team.leave:
    default: op
  uhc.team.list:
    default: op